server:
  port: 22222


management:
  health:
    rabbit:
      # 看着控制台异常费解
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Hxx&Wyj_22-3-8@private
    username: root
    url: jdbc:mysql://rm-bp1h5384h1ot9ztbrfo.mysql.rds.aliyuncs.com:3306/aigo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
